/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as deFiCrowdFundingSol from "./DeFiCrowdFunding.sol";
export type { deFiCrowdFundingSol };
export type { Lock } from "./Lock";
