/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as automation from "./automation";
export type { automation };
import type * as shared from "./shared";
export type { shared };
